---
-name: Create Directory
 host:g1

  tasks:
    -name: create directory
    file:
      path: /home/centos/NewDir_fromPlayG1
      state: directory



- name: Install a list of packages
  host:n1

  tasks:
  -name: Install a list of packages
    yum:
      name:
       - git
       - httpd
       - wget
      state: present
...