---
- name: Deploy Flask Application
  hosts: flask_app_node
  become: yes
  vars:
    venv_path: myprojectenv
  tasks:
    - name: Ensure Python 3 virtualenv is installed
      yum:
        name: python3-venv
        state: present

    - name: Clone the Flask application repository
      git:
        repo: https://github.com/davechibuike/flask_app_Project.git
        dest: /opt/flask_app
        force: yes

    - name: Set up Python virtual environment
      command: python3 -m venv /opt/flask_app/{{ venv_path }}
      args:
        creates: /opt/flask_app/{{ venv_path }}

    - name: Install Flask application dependencies
      pip:
        requirements: /opt/flask_app/requirements.txt
        virtualenv: /opt/flask_app/{{ venv_path }}

    - name: Configure Gunicorn systemd service
      template:
        src: gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
      notify: Restart Gunicorn

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

  handlers:
    - name: Restart Gunicorn
      systemd:
        name: gunicorn
        state: restarted

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
