---
- name: Install Jenkins
  hosts: jenkins_ansible
  become: true
  tasks:
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    -name: Enable and start jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
