- name: Install Jenkins
  hosts: jenkins_ansible
  become: true
  tasks:
    - name: Add Jenkins repository key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io.key
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Enable and start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
